# Generated by Django 3.2.5 on 2022-01-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=200)),
                ('artifact_id', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('favorite', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
