name: gestoven
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - asgiref=3.4.1
  - attrs=21.4.0
  - black=19.10b0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2020.6.20
  - click=8.0.3
  - django=3.2.5
  - django-grappelli=3.0.2
  - djangorestframework=3.13.1
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - libedit=3.1.20210910
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpq=12.9
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pathspec=0.7.0
  - pip=21.2.4
  - psycopg2=2.8.6
  - python=3.10.0
  - pytz=2021.3
  - readline=8.1.2
  - regex=2021.8.3
  - setuptools=58.0.4
  - sqlite=3.37.0
  - sqlparse=0.4.1
  - tk=8.6.11
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
